# Scholarship Recommendation System


This content-based scholarship recommendation system involved:

**Tasks:** Data loading and initial exploration, data cleaning (duplicates, nulls, column removal), text preprocessing (combining, cleaning, vectorization), cosine similarity calculation, and creating a recommendation function. The final DataFrame and similarity matrix were saved.

**Problem Faced:** Stemming was applied but not correctly reassigned to the DataFrame, leaving 'clean_text' with unstemmed words, which could affect recommendation accuracy.

**My Contributions:** Generated code for data handling, text processing, model development, and provided descriptive explanations for each step, including identifying and explaining the stemming issue.

Imports the pandas library.

In [ ]:
import pandas as pd

Loads the `international_scholarships_cleaned.csv` into a DataFrame.

In [ ]:
df = pd.read_csv('/content/international_scholarships_cleaned.csv')

Displays the DataFrame's shape (rows, columns).

In [ ]:
df.shape

(10410, 7)

Displays the entire DataFrame content.

In [ ]:
df

,Scholarship Name,Deadline,Amount,Description,Location,Years,Link
0,Order Sons of Italy in America National Leader...,Unknown deadline,500.0,Applicant must be of Italian heritage and be a...,No Geographic Restrictions,"['College junior', 'College freshman', 'Colleg...",https://www.collegescholarships.org/financial-...
1,Entrance Scholarship,Unknown deadline,500.0,Applicant must be an incoming first-year stude...,No Geographic Restrictions,['College freshman'],https://www.collegescholarships.org/financial-...
2,Agnes Jones Jackson Scholarship,Unknown deadline,500.0,Applicant must be current member of the NAACP ...,No Geographic Restrictions,"['College freshman', 'Master&#039;s-level stud...",https://www.collegescholarships.org/financial-...
3,Fellowship in Jewish Studies,Unknown deadline,500.0,Applicant must have an interest in Jewish stud...,No Geographic Restrictions,['High school senior'],https://www.collegescholarships.org/financial-...
4,Doctoral Scholarship,Unknown deadline,500.0,Applicant must be a doctoral student specializ...,No Geographic Restrictions,['Doctoral-level study'],https://www.collegescholarships.org/financial-...
...,...,...,...,...,...,...,...
10405,Annual Fund Award for Excellence,Unknown deadline,500.0,Applicant must have a minimum SAT score of 1100.,No Geographic Restrictions,['College freshman'],https://www.collegescholarships.org/financial-...
10406,N. Rose Atwood Scholarship,Unknown deadline,500.0,Applicant must be a Maryland resident with a m...,No Geographic Restrictions,['College freshman'],https://www.collegescholarships.org/financial-...
10407,Emma and Paul Dailey Scholarship,Unknown deadline,500.0,Applicant must have a minimum SAT score of 110...,Maryland,['College freshman'],https://www.collegescholarships.org/financial-...
10408,Donald Donahue Tri-State Scholarship,Unknown deadline,500.0,Applicant must have a minimum SAT score of 110...,No Geographic Restrictions,['College freshman'],https://www.collegescholarships.org/financial-...
10409,Lewis J. Ort Access to Education Award,Unknown deadline,500.0,Applicant must demonstrate academic ability an...,"Bedford, Berkeley, Franklin, Fulton, Grant, Ha...",['College freshman'],https://www.collegescholarships.org/financial-...

Counts unique values in the 'Years' column.

In [ ]:
df['Years'].value_counts()

Years
['College freshman']                                                                                                                                                    2878
['No Restrictions']                                                                                                                                                     1738
['Master&#039;s-level study']                                                                                                                                            253
['College senior', 'College junior']                                                                                                                                     219
['College junior', 'College senior']                                                                                                                                     184
                                                                                                                                                                        ...
['College senior', 'College junior', 'College sophomore', 'College freshman', 'High school senior']                                                                        1
['High school senior', 'College sophomore', 'College freshman']                                                                                                            1
['College junior', 'Other postgraduate-level study', 'College senior', 'Master&#039;s-level study', 'College freshman', 'College sophomore']                               1
['College senior', 'College junior', 'College sophomore', 'Other postgraduate-level study', 'Doctoral-level study', 'Master&#039;s-level study', 'College freshman']       1
['College sophomore', 'Master&#039;s-level study', 'Other postgraduate-level study', 'College junior', 'College senior', 'Doctoral-level study', 'College freshman']       1
Name: count, Length: 761, dtype: int64

Counts unique values in the 'Amount' column.

In [ ]:
df['Amount'].value_counts()

Amount
500.0    9646
750.0      85
600.0      74
250.0      68
400.0      63
         ...
230.0       1
770.0       1
840.0       1
694.0       1
660.0       1
Name: count, Length: 96, dtype: int64

Shows DataFrame information (datatypes, non-null counts).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10410 entries, 0 to 10409
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Scholarship Name  10410 non-null  object
 1   Deadline          10410 non-null  object
 2   Amount            10410 non-null  float64
 3   Description       10410 non-null  object
 4   Location          10410 non-null  object
 5   Years             10410 non-null  object
 6   Link              10410 non-null  object
dtypes: float64(1), object(6)
memory usage: 569.4+ KB

Checks for null values across all columns.

In [ ]:
df.isnull().sum()

Scholarship Name    0
Deadline            0
Amount              0
Description         0
Location            0
Years               0
Link                0
dtype: int64

Removes duplicate rows from the DataFrame.

In [ ]:
df = df.drop_duplicates()

Displays DataFrame's shape after removing duplicates.

In [ ]:
df.shape

(10410, 7)

Drops 'Deadline' and 'Link' columns.

In [ ]:
df = df.drop(['Deadline','Link'],axis=1)

Displays the head of the DataFrame after column removal.

In [ ]:
df.head()

,Scholarship Name,Amount,Description,Location,Years
0,Order Sons of Italy in America National Leader...,500.0,Applicant must be of Italian heritage and be a...,No Geographic Restrictions,"['College junior', 'College freshman', 'Colleg..."
1,Entrance Scholarship,500.0,Applicant must be an incoming first-year stude...,No Geographic Restrictions,['College freshman']
2,Agnes Jones Jackson Scholarship,500.0,Applicant must be current member of the NAACP ...,No Geographic Restrictions,"['College freshman', 'Master&#039;s-level stud..."
3,Fellowship in Jewish Studies,500.0,Applicant must have an interest in Jewish stud...,No Geographic Restrictions,['High school senior']
4,Doctoral Scholarship,500.0,Applicant must be a doctoral student specializ...,No Geographic Restrictions,['Doctoral-level study']

Displays the DataFrame's shape after column removal.

In [ ]:
df.shape

(10410, 5)

Drops rows with nulls in specified key columns.

In [ ]:
df = df.dropna(subset=['Scholarship Name','Amount','Description','Location','Years'])

Displays the DataFrame's shape after dropping nulls.

In [ ]:
df.shape

(10410, 5)

Displays the head of the DataFrame after null handling.

In [ ]:
df.head()

,Scholarship Name,Amount,Description,Location,Years
0,Order Sons of Italy in America National Leader...,500.0,Applicant must be of Italian heritage and be a...,No Geographic Restrictions,"['College junior', 'College freshman', 'Colleg..."
1,Entrance Scholarship,500.0,Applicant must be an incoming first-year stude...,No Geographic Restrictions,['College freshman']
2,Agnes Jones Jackson Scholarship,500.0,Applicant must be current member of the NAACP ...,No Geographic Restrictions,"['College freshman', 'Master&#039;s-level stud..."
3,Fellowship in Jewish Studies,500.0,Applicant must have an interest in Jewish stud...,No Geographic Restrictions,['High school senior']
4,Doctoral Scholarship,500.0,Applicant must be a doctoral student specializ...,No Geographic Restrictions,['Doctoral-level study']

Combines 'Description', 'Location', and 'Years' into a new 'Des' column.

In [ ]:
df['Des'] = df['Description'] + df['Location']  + df['Years']

Displays the head of the DataFrame including the new 'Des' column.

In [ ]:
df.head()

,Scholarship Name,Amount,Description,Location,Years,Des
0,Order Sons of Italy in America National Leader...,500.0,Applicant must be of Italian heritage and be a...,No Geographic Restrictions,"['College junior', 'College freshman', 'Colleg...",Applicant must be of Italian heritage and be a...
1,Entrance Scholarship,500.0,Applicant must be an incoming first-year stude...,No Geographic Restrictions,['College freshman'],Applicant must be an incoming first-year stude...
2,Agnes Jones Jackson Scholarship,500.0,Applicant must be current member of the NAACP ...,No Geographic Restrictions,"['College freshman', 'Master&#039;s-level stud...",Applicant must be current member of the NAACP ...
3,Fellowship in Jewish Studies,500.0,Applicant must have an interest in Jewish stud...,No Geographic Restrictions,['High school senior'],Applicant must have an interest in Jewish stud...
4,Doctoral Scholarship,500.0,Applicant must be a doctoral student specializ...,No Geographic Restrictions,['Doctoral-level study'],Applicant must be a doctoral student specializ...

Defines a function to clean text data (lowercase, remove HTML, URLs, numbers, punctuation).

In [ ]:
import re
import string
from bs4 import BeautifulSoup

def clean_text(text):
  text = text.lower()
  text = BeautifulSoup(text, "html.parser").get_text()
  text = re.sub(r'http\S+|www\S+', '', text)
  text = re.sub(r'\d+', '', text)
  text = text.translate(str.maketrans('', '', string.punctuation))
  text = re.sub(r'\W+', ' ', text)
  text = re.sub(r'\s+', ' ', text).strip()
  return text

Applies the `clean_text` function to the 'Des' column, creating 'clean_text'.

In [ ]:
df['clean_text'] = df['Des'].apply(clean_text)

Displays the head of the DataFrame with the 'clean_text' column.

In [ ]:
df.head()

,Scholarship Name,Amount,Description,Location,Years,Des,clean_text
0,Order Sons of Italy in America National Leader...,500.0,Applicant must be of Italian heritage and be a...,No Geographic Restrictions,"['College junior', 'College freshman', 'Colleg...",Applicant must be of Italian heritage and be a...,applicant must be of italian heritage and be a...
1,Entrance Scholarship,500.0,Applicant must be an incoming first-year stude...,No Geographic Restrictions,['College freshman'],Applicant must be an incoming first-year stude...,applicant must be an incoming firstyear studen...
2,Agnes Jones Jackson Scholarship,500.0,Applicant must be current member of the NAACP ...,No Geographic Restrictions,"['College freshman', 'Master&#039;s-level stud...",Applicant must be current member of the NAACP ...,applicant must be current member of the naacp ...
3,Fellowship in Jewish Studies,500.0,Applicant must have an interest in Jewish stud...,No Geographic Restrictions,['High school senior'],Applicant must have an interest in Jewish stud...,applicant must have an interest in jewish stud...
4,Doctoral Scholarship,500.0,Applicant must be a doctoral student specializ...,No Geographic Restrictions,['Doctoral-level study'],Applicant must be a doctoral student specializ...,applicant must be a doctoral student specializ...

Prints a sample of the cleaned text for inspection.

In [ ]:
for i in range(0,1000):
  print("_________")
  print(df['clean_text'].iloc[i])

_________
applicant must be of italian heritage and be a fulltime student attending or planning on attending an accredited fouryear institution who has demonstrated exceptional leadership qualities and a distinguished level of scholastic achievement recipients will be officially recognized in may at the sifs national education leadership awards nela gala in washington dc monetary awards are presented directly to students academic institutions in accordance with eligibility requirementsno geographic restrictionscollege junior college freshman college senior college sophomore
_________
applicant must be an incoming firstyear student selection based upon portfolio rating gpa and sat reasoningact scoreno geographic restrictionscollege freshman
_________
applicant must be current member of the naacp and must not have reached the age of by the application deadline applicant must be a citizen of the united states and be enrolled in an accredited college or university in the united states undergraduate students must be fulltime with a gpa of at least c graduate students may be full or parttime with a gpa of b applicant must demonstrate financial need renewal of the agnes jones jackson scholarship is competitive please refer to the naacp national website or call the naacp national education department at for more informationno geographic restrictionscollege freshman masterslevel study college senior doctorallevel study college sophomore college junior
_________
applicant must have an interest in jewish studies award is to assist wellqualified individuals in carrying out an independent scholarly literary or art project in a field of jewish specialization which makes a significant contribution to the understanding preservation enhancement or transmission of jewish cultureno geographic restrictionshigh school senior
_________
applicant must be a doctoral student specializing in jewish fields priority is given to candidates whose dissertation topics have been approvedno geographic restrictionsdoctorallevel study
_________
applicant must be of armenian heritage be a fulltime graduate student seeking a masters or doctorate degree at a highly or mostcompetitive us institution and have a minimum gpa in undergraduate workno geographic restrictionsmasterslevel study
_________
applicant must be jewish be a resident of the san francisco bay area and have a cosigner who resides in the bay areasan franciscocollege sophomore college junior masterslevel study other postgraduatelevel study college senior college freshman doctorallevel study
_________
applicant must be jewish reside in marin county san francisco county san mateo county or sonoma county calif and demonstrate academic achievement promise and financial needmarin san francisco san mateo sonomacollege senior college freshman college junior college sophomore
_________
applicant must be jewish be under age demonstrate financial need and be a resident of marin san francisco san mateo or sonoma county calif award is for a study trip to israelmarin san francisco san mateo sonomacollege sophomore masterslevel study other postgraduatelevel study college junior college senior doctorallevel study college freshman
_________
applicant must be jewish be under age demonstrate financial need and be a resident of marin san francisco san mateo or sonoma county califmarin san francisco san mateo sonomacollege senior college junior college sophomore other postgraduatelevel study doctorallevel study masterslevel study college freshman
_________
applicant must be the child of a deceased disabled or combat veteran or veteran listed as a powmia the veteran must have been a legal resident of north carolina at the time of entry into service or the child must have been born in north carolina and resided there continuously since birth applicant must be attending a school in north carolinanorth carolinacollege freshman college sophomore college senior college junior
_________
applicant must be the child or grandchild of a veteran of world war i world war ii korean conflict vietnam conflict beirutgranada emergency or panama emergency applicant must attend an alabama statesupported college selfaddressed stamped envelope is required to receive applicationalabamacollege senior college junior college sophomore college freshman
_________
applicant must be a participant in the iowa american legion baseball tournament and portray outstanding sportsmanship team play and athletic ability selection is by the state baseball committeeiowacollege freshman
_________
applicant must be a finalist in the oratorical contestmichigancollege freshman
_________
applicant must be a winner of the nebraska department oratorical contestnebraskacollege freshman
_________
applicant must be a high school senior or graduate under years of age a new york state resident the child or grandchild of a veteran and be pursuing a career in medical or teaching fieldsnew yorkcollege freshman
_________
applicant must be a us citizen or permanent resident enrolled in a course of study relating to a degree in nuclear science and technology applicant must be sponsored by an ans local section division student branch committee member or organization memberno geographic restrictionsdoctorallevel study masterslevel study
_________
applicant must be a us citizen and have a minimum gpa selection is based upon financial need academic achievement and personal and professional goals two reference forms from two dental school representatives ie professor or academic advisor in support of the application must be submitted as part of the application formno geographic restrictionscollege junior college sophomore college senior
_________
applicant must be employed by the halton companywashington oregoncollege sophomore college freshman
_________
selection is based upon interest in and a commitment to a career in medical assisting financial need academic ability and demonstration of involvement in school and community award is limited to individuals enrolled in a postsecondary program accredited by the commission on accreditation of allied health education programs caahep students studying other allied health professions or planning to enter medical school are not eligibleno geographic restrictionscollege freshman college sophomore
_________
applicant must be the child of a navy supply corps officer including warrant or associated supply enlisted ratings on active duty in reserve status retiredwithpay or deceased and have a minimum gpa selection is based upon scholastic ability character leadership and financial needno geographic restrictionscollege freshman college senior college sophomore college junior
_________
applicant must be enrolled full time in a new york state school or college be a new york resident at the start of the term for which payment is requested and be the child of a veteran who served in the us armed forces during specified periods of war or national emergency and as a result of service died or suffered a or more disability was a pow or is currently classified as mia veteran parent must have been a new york resident at the time of entry into service or at deathnew yorkhigh school sophomore high school junior high school freshman college sophomore college senior college freshman college junior high school senior
_________
applicant must be the child or spouse of a new york police officer firefighter or peace officer and a new york resident attending a new york school at the start of the term for which payment is requested parent must have died as a result of injury sustained in the line of duty award is actual tuition cost or suny undergraduate tuition whichever is lessnew yorkcollege sophomore college senior college freshman college junior
_________
applicant must be a woman who is properly qualified and has proven ability by several years experience awards are made in recognition of leadership in cooperative extension work and initiative in scientific research applicant must submit a letter of application plan of study testimonials of character ability personality small recent photograph and scholarship theses papers or reports and a certificate from the registrar of degrees awardedno geographic restrictionsdoctorallevel study masterslevel study college senior
_________
applicant must be a current employee who is enrolled in a nursing or allied health eg radiology technology respiratory therapy medical technology physical therapy physical therapy assistant occupational therapy or physician assistant undergraduate program or a nonemployee who is enrolled in a nursing program leading to a bsn or higher minimum gpa two letters of recommendation transcript and letter of acceptancegood standing required award requires a work commitment at suburban hospital in bethesda md upon completion of degree programno geographic restrictionsother postgraduatelevel study masterslevel study college junior college senior doctorallevel study
_________
applicant must be a us citizen and a fulltime aviation career employee parttime study must be directed toward enhancing job skillsno geographic restrictionsmasterslevel study college junior college sophomore college senior doctorallevel study college freshman
_________
applicant must be a high school senior who is a citizen of the united states selection is based upon scholarship leadership and financial needunited stateshigh school senior
_________
applicant must be a high school senior with a minimum gpa who is a member in good standing of their nhs chapter and has been nominated by his or her local chapter each national honor society chapter may nominate two applicants based on leadership scholarship character and service contact your local national honor society adviser for further informationno geographic restrictionshigh school senior
_________
selection is based upon scholastic achievement career goals leadership skills and determination scholarship must be used at a fouryear college or university in californiacaliforniano restrictions
_________
applicant must be a minority who is a fulltime student entering the fall term of their final year of classroom work in a healthcare management graduate program applicant must be a student associate of the american college of healthcare executives financial aid must be demonstratedno geographic restrictionsmasterslevel study doctorallevel study
_________
applicant must be a high school junior participating in the new jersey american legion baseball programnew jerseyno restrictions
_________
applicant must be enrolled as a fulltime student in an accredited us institution with a minimum gpa and an intention to make atmospheric science a career selection is based upon academic excellence and achievementunited statescollege senior
_________
applicant must attend a school accredited by the national architectural accrediting board or recognized by the royal architectural institute of canada selection is based upon statement of goals academic performance recommendations and financial need application available only through schoolsno geographic restrictionsno restrictions
_________
applicant must submit typed application full resume of education and employment official transcripts and a twopart statement not to exceed words preference is given to mature scholars of demonstrated ability award is for study or research at the metropolitan museum of artno geographic restrictionsother postgraduatelevel study doctorallevel study
_________
applicant must be a resident of hawaii for at least one year rank in top quarter of class have a minimum gpa and show a financial need must also demonstrate the ability industriousness dependability and determination needed to succeed in business within the pacific basin area official high schoolcollege transcripts through first semester of current year two letters of recommendation fafsa student aid report and sat reasoningact scores requiredhawaiicollege senior college junior college sophomore college freshman
_________
applicant must be a graduating senior from a high school in the county area of northwest kansas have a minimum gpa and plan on attending an accredited school in kansascheyenne cloud decatur ellis ellsworth gove graham jewell lincoln logan mitchell norton osborne ottawa phillips rawlins republic rooks russell saline sheridan sherman smith thomas trego wallacehigh school senior
_________
applicant must be a us citizen and a texas resident attending a college or university full time in texas and have a minimum gpa undergraduate or a minimum gpa graduate selection is based upon academics financial need may be consideredamarillo austin corpus christi dallas el paso fort worth houston kingsville lubbock san antonio texarkana tyler victoriacollege senior college sophomore college junior
_________
applicant must be a graduate of gordon lee memorial high school in chickamauga gachickamaugacollege freshman college sophomore college senior college junior
_________
applicant must be an africanamerican high school senior who is graduating from an accredited public or private high school in alexandria arlington loudon prince william or fairfax county applicant must have been accepted to or have applied to an accredited college or university in the united states and plan to enroll as a fulltime student in a program leading to a bachelors degree minimum gpa and demonstration of communication skills leadership skills and community involvement are requiredalexandria city arlington fairfax loudoun prince williamhigh school senior
_________
applicant must be from new york city who comes from a lowincome familynew yorkhigh school senior
_________
applicant must be a fulltime graduate student selection is based upon academic promise and outstanding academic achievement one scholarship gives priority to foreign or minority students studying in the continental us another gives priority to disabled students and another gives priority to a minority student masters level students must be enrolled in or accepted to a program ccredited by te american speechlanguagehearing association council on academic accreditationunited statesdoctorallevel study masterslevel study
_________
applicant must be a us citizen a minority and be accepted for fulltime study in a graduate program applicant must submit a formal application masters level students must be enrolled in or accepted to a program accredited by te american speechlanguagehearing association council on academic accreditationno geographic restrictionsdoctorallevel study masterslevel study
_________
applicant must be a us citizen a woman and have a minimum gpa applicant must be in an abetaccredited engineering program engineering at sweapproved institution or computer science in a csabaccredited program or at an abetaccredited or sweapproved institutionno geographic restrictionscollege freshman
_________
applicant must be a boy scout who exhibits outstanding service to his religious institution school and community and has received the eagle scout award selection is by the boy scout committee award must be used in state of iowaiowacollege freshman
_________
applicant must be a mortarboard member or alumnino geographic restrictionscollege senior
_________
awarded on a competitive basis for a proposed research project for the exploration of new applications of geotechnical engineering or the earth sciences to social economic environmental and political issuesno geographic restrictionsmasterslevel study other postgraduatelevel study doctorallevel study
_________
applicant must be an asce national student member not more than two applications per student chapter may be submitted selection is based upon the appraisal of the applicants justification of the award educational plan academic performance and standing potential for development leadership capacity and financial needno geographic restrictionscollege freshman college senior college sophomore college junior
_________
applicant must be a college senior enrolled in an abet or acceaccredited or candidate status construction or civil engineering program or possess an undergraduate construction or civil engineering degree from such an accredited program applicant must be enrolled or planning to enroll as a fulltime student in a construction graduate degree program or parttime student in one of the sponsors recognized masters programs for the fall term one full academic year is required to remain in the applicants schooling application evaluation forms and transcript are requiredunited statesmasterslevel study college senior doctorallevel study
_________
applicant must be a college sophomore or junior enrolled or planning to enroll in a fulltime four or fiveyear abet or acceaccredited construction management or constructionrelated engineering program application evaluation forms and transcript are requiredunited statescollege senior college junior college sophomore
_________
applicant must have a major that is considered beneficial to the new york state water works selection is based upon academic achievement and extracurricular activitiesnew yorkcollege senior college junior
_________
applicant must be a us citizen or permanent us resident must have been a resident of virginia for at least one year prior to the deadline must be enrolled full time at an accredited college university or school of the arts and must submit slides of artwork for art three films for filmvideo or three research papers for art historyvirginiamasterslevel study college senior doctorallevel study college sophomore college freshman college junior
_________
applicant must be a us citizen be a phd candidate have completed all requirements for the phd except the dissertation and have a dissertation topic focused on the history of visual arts of the us applicant must be enrolled at a us institution applications must be submitted through the acls online fellowship application system ofa ofa is accessible through the fellowship and grant programs section of the web siteno geographic restrictionsmasterslevel study doctorallevel study
_________
applicant must be a recently ordained rabbi award looks to help recipient obtain advanced training as a judge on rabbinical courts heads of institutions of higher learning or other advanced religious leadership positionsno geographic restrictionsno restrictions
_________
applicant must have a minimum gpa and major in the food science or food technology fieldsno geographic restrictionsdoctorallevel study masterslevel study
_________
applicant must have a minimum gpa conduct research in the area of food science or food technology and must demonstrate an interest in researchno geographic restrictionsmasterslevel study doctorallevel study
_________
applicant must be a connecticut resident with a predoctoral degree in dental medicineno geographic restrictionshigh school junior
_________
applicant must be an outstanding graduate student in school administration who intends to make school superintendency a careerno geographic restrictionsmasterslevel study other postgraduatelevel study doctorallevel study
_________
applicant must be a recent graduate of a new hampshire high school who will be entering his or her first year of college to study education applicant must have a minimum grade average of bnew hampshirecollege freshman
_________
applicant must be a fulltime graduate student in any field of education and a member in good standing of phi delta kappa selection based upon written essay transcript recommendation and involvement with phi delta kappano geographic restrictionsmasterslevel study other postgraduatelevel study doctorallevel study
_________
applicant must be a black or hispanic indiana resident with a minimum gpa who agrees to teach in indiana upon certification award may be used at indiana schools onlyindianacollege freshman college sophomore college senior college junior
_________

Performs stemming using NLTK's PorterStemmer. Problem: The stemmed words are printed as a list but not assigned back to the DataFrame, meaning the 'clean_text' column still contains unstemmed words, potentially affecting text processing.

In [ ]:
import nltk
from nltk.stem import PorterStemmer

porter_stemmer = PorterStemmer()


stemmed_words = [porter_stemmer.stem(word) for word in df['clean_text']]

print("Stemmed words:", stemmed_words)

Stemmed words: ['applicant must be of italian heritage and be a fulltime student attending or planning on attending an accredited fouryear institution who has demonstrated exceptional leadership qualities and a distinguished level of scholastic achievement recipients will be officially recognized in may at the sifs national education leadership awards nela gala in washington dc monetary awards are presented directly to students academic institutions in accordance with eligibility requirementsno geographic restrictionscollege junior college freshman college senior college sophomor', 'applicant must be an incoming firstyear student selection based upon portfolio rating gpa and sat reasoningact scoreno geographic restrictionscollege freshman', 'applicant must be current member of the naacp and must not have reached the age of by the application deadline applicant must be a citizen of the united states and be enrolled in an accredited college or university in the united states undergraduate students must be fulltime with a gpa of at least c graduate students may be full or parttime with a gpa of b applicant must demonstrate financial need renewal of the agnes jones jackson scholarship is competitive please refer to the naacp national website or call the naacp national education department at for more informationno geographic restrictionscollege freshman masterslevel study college senior doctorallevel study college sophomore college junior', 'applicant must have an interest in jewish studies award is to assist wellqualified individuals in carrying out an independent scholarly literary or art project in a field of jewish specialization which makes a significant contribution to the understanding preservation enhancement or transmission of jewish cultureno geographic restrictionshigh school senior', 'applicant must be a doctoral student specializing in jewish fields priority is given to candidates whose dissertation topics have been approvedno geographic restrictionsdoctorallevel studi', 'applicant must be of armenian heritage be a fulltime graduate student seeking a masters or doctorate degree at a highly or mostcompetitive us institution and have a minimum gpa in undergraduate workno geographic restrictionsmasterslevel studi', 'applicant must be jewish be a resident of the san francisco bay area and have a cosigner who resides in the bay areasan franciscocollege sophomore college junior masterslevel study other postgraduatelevel study college senior college freshman doctorallevel studi', 'applicant must be jewish reside in marin county san francisco county san mateo county or sonoma county calif and demonstrate academic achievement promise and financial needmarin san francisco san mateo sonomacollege senior college freshman college junior college sophomor', 'applicant must be jewish be under age demonstrate financial need and be a resident of marin san francisco san mateo or sonoma county calif award is for a study trip to israelmarin san francisco san mateo sonomacollege sophomore masterslevel study other postgraduatelevel study college junior college senior doctorallevel study college freshman', 'applicant must be jewish be under age demonstrate financial need and be a resident of marin san francisco san mateo or sonoma county califmarin san francisco san mateo sonomacollege senior college junior college sophomore other postgraduatelevel study doctorallevel study masterslevel study college freshman', 'applicant must be the child of a deceased disabled or combat veteran or veteran listed as a powmia the veteran must have been a legal resident of north carolina at the time of entry into service or the child must have been born in north carolina and resided there continuously since birth applicant must be attending a school in north carolinanorth carolinacollege freshman college sophomore college senior college junior', 'applicant must be the child or grandchild of a veteran of world war i world war ii korean conflict vietnam conflict beirutgranada emergency or panama emergency applicant must attend an alabama statesupported college selfaddressed stamped envelope is required to receive applicationalabamacollege senior college junior college sophomore college freshman', 'applicant must be a participant in the iowa american legion baseball tournament and portray outstanding sportsmanship team play and athletic ability selection is by the state baseball committeeiowacollege freshman', 'applicant must be a finalist in the oratorical contestmichigancollege freshman', 'applicant must be a winner of the nebraska department oratorical contestnebraskacollege freshman', 'applicant must be a high school senior or graduate under years of age a new york state resident the child or grandchild of a veteran and be pursuing a career in medical or teaching fieldsnew yorkcollege freshman', 'applicant must be a us citizen or permanent resident enrolled in a course of study relating to a degree in nuclear science and technology applicant must be sponsored by an ans local section division student branch committee member or organization memberno geographic restrictionsdoctorallevel study masterslevel studi', 'applicant must be a us citizen and have a minimum gpa selection is based upon financial need academic achievement and personal and professional goals two reference forms from two dental school representatives ie professor or academic advisor in support of the application must be submitted as part of the application formno geographic restrictionscollege junior college sophomore college senior', 'applicant must be employed by the halton companywashington oregoncollege sophomore college freshman', 'selection is based upon interest in and a commitment to a career in medical assisting financial need academic ability and demonstration of involvement in school and community award is limited to individuals enrolled in a postsecondary program accredited by the commission on accreditation of allied health education programs caahep students studying other allied health professions or planning to enter medical school are not eligibleno geographic restrictionscollege freshman college sophomor', 'applicant must be the child of a navy supply corps officer including warrant or associated supply enlisted ratings on active duty in reserve status retiredwithpay or deceased and have a minimum gpa selection is based upon scholastic ability character leadership and financial needno geographic restrictionscollege freshman college senior college sophomore college junior', 'applicant must be enrolled full time in a new york state school or college be a new york resident at the start of the term for which payment is requested and be the child of a veteran who served in the us armed forces during specified periods of war or national emergency and as a result of service died or suffered a or more disability was a pow or is currently classified as mia veteran parent must have been a new york resident at the time of entry into service or at deathnew yorkhigh school sophomore high school junior high school freshman college sophomore college senior college freshman college junior high school senior', 'applicant must be the child or spouse of a new york police officer firefighter or peace officer and a new york resident attending a new york school at the start of the term for which payment is requested parent must have died as a result of injury sustained in the line of duty award is actual tuition cost or suny undergraduate tuition whichever is lessnew yorkcollege sophomore college senior college freshman college junior', 'applicant must be a woman who is properly qualified and has proven ability by several years experience awards are made in recognition of leadership in cooperative extension work and initiative in scientific research applicant must submit a letter of application plan of study testimonials of character ability personality small recent photograph and scholarship theses papers or reports and a certificate from the registrar of degrees awardedno geographic restrictionsdoctorallevel study masterslevel study college senior', 'applicant must be a current employee who is enrolled in a nursing or allied health eg radiology technology respiratory therapy medical technology physical therapy physical therapy assistant occupational therapy or physician assistant undergraduate program or a nonemployee who is enrolled in a nursing program leading to a bsn or higher minimum gpa two letters of recommendation transcript and letter of acceptancegood standing required award requires a work commitment at suburban hospital in bethesda md upon completion of degree programno geographic restrictionsother postgraduatelevel study masterslevel study college junior college senior doctorallevel studi', 'applicant must be a us citizen and a fulltime aviation career employee parttime study must be directed toward enhancing job skillsno geographic restrictionsmasterslevel study college junior college sophomore college senior doctorallevel study college freshman', 'applicant must be a high school senior who is a citizen of the united states selection is based upon scholarship leadership and financial needunited stateshigh school senior', 'applicant must be a high school senior with a minimum gpa who is a member in good standing of their nhs chapter and has been nominated by his or her local chapter each national honor society chapter may nominate two applicants based on leadership scholarship character and service contact your local national honor society adviser for further informationno geographic restrictionshigh school senior', 'selection is based upon scholastic achievement career goals leadership skills and determination scholarship must be used at a fouryear college or university in californiacaliforniano restrict', 'applicant must be a minority who is a fulltime student entering the fall term of their final year of classroom work in a healthcare management graduate program applicant must be a student associate of the american college of healthcare executives financial aid must be demonstratedno geographic restrictionsmasterslevel study doctorallevel studi', 'applicant must be a high school junior participating in the new jersey american legion baseball programnew jerseyno restrict', 'applicant must be enrolled as a fulltime student in an accredited us institution with a minimum gpa and an intention to make atmospheric science a career selection is based upon academic excellence and achievementunited statescollege senior', 'applicant must attend a school accredited by the national architectural accrediting board or recognized by the royal architectural institute of canada selection is based upon statement of goals academic performance recommendations and financial need application available only through schoolsno geographic restrictionsno restrict', 'applicant must submit typed application full resume of education and employment official transcripts and a twopart statement not to exceed words preference is given to mature scholars of demonstrated ability award is for study or research at the metropolitan museum of artno geographic restrictionsother postgraduatelevel study doctorallevel studi', 'applicant must be a resident of hawaii for at least one year rank in top quarter of class have a minimum gpa and show a financial need must also demonstrate the ability industriousness dependability and determination needed to succeed in business within the pacific basin area official high schoolcollege transcripts through first semester of current year two letters of recommendation fafsa student aid report and sat reasoningact scores requiredhawaiicollege senior college junior college sophomore college freshman', 'applicant must be a graduating senior from a high school in the county area of northwest kansas have a minimum gpa and plan on attending an accredited school in kansascheyenne cloud decatur ellis ellsworth gove graham jewell lincoln logan mitchell norton osborne ottawa phillips rawlins republic rooks russell saline sheridan sherman smith thomas trego wallacehigh school senior', 'applicant must be a us citizen and a texas resident attending a college or university full time in texas and have a minimum gpa undergraduate or a minimum gpa graduate selection is based upon academics financial need may be consideredamarillo austin corpus christi dallas el paso fort worth houston kingsville lubbock san antonio texarkana tyler victoriacollege senior college sophomore college junior', 'applicant must be a graduate of gordon lee memorial high school in chickamauga gachickamaugacollege freshman college sophomore college senior college junior', 'applicant must be an africanamerican high school senior who is graduating from an accredited public or private high school in alexandria arlington loudon prince william or fairfax county applicant must have been accepted to or have applied to an accredited college or university in the united states and plan to enroll as a fulltime student in a program leading to a bachelors degree minimum gpa and demonstration of communication skills leadership skills and community involvement are requiredalexandria city arlington fairfax loudoun prince williamhigh school senior', 'applicant must be from new york city who comes from a lowincome familynew yorkhigh school senior', 'applicant must be a fulltime graduate student selection is based upon academic promise and outstanding academic achievement one scholarship gives priority to foreign or minority students studying in the continental us another gives priority to disabled students and another gives priority to a minority student masters level students must be enrolled in or accepted to a program ccredited by te american speechlanguagehearing association council on academic accreditationunited statesdoctorallevel study masterslevel studi', 'applicant must be a us citizen a minority and be accepted for fulltime study in a graduate program applicant must submit a formal application masters level students must be enrolled in or accepted to a program accredited by te american speechlanguagehearing association council on academic accreditationno geographic restrictionsdoctorallevel study masterslevel studi', 'applicant must be a us citizen a woman and have a minimum gpa applicant must be in an abetaccredited engineering program engineering at sweapproved institution or computer science in a csabaccredited program or at an abetaccredited or sweapproved institutionno geographic restrictionscollege freshman', 'applicant must be a boy scout who exhibits outstanding service to his religious institution school and community and has received the eagle scout award selection is by the boy scout committee award must be used in state of iowaiowacollege freshman', 'applicant must be a mortarboard member or alumnino geographic restrictionscollege senior', 'awarded on a competitive basis for a proposed research project for the exploration of new applications of geotechnical engineering or the earth sciences to social economic environmental and political issuesno geographic restrictionsmasterslevel study other postgraduatelevel study doctorallevel studi', 'applicant must be an asce national student member not more than two applications per student chapter may be submitted selection is based upon the appraisal of the applicants justification of the award educational plan academic performance and standing potential for development leadership capacity and financial needno geographic restrictionscollege freshman college senior college sophomore college junior', 'applicant must be a college senior enrolled in an abet or acceaccredited or candidate status construction or civil engineering program or possess an undergraduate construction or civil engineering degree from such an accredited program applicant must be enrolled or planning to enroll as a fulltime student in a construction graduate degree program or parttime student in one of the sponsors recognized masters programs for the fall term one full academic year is required to remain in the applicants schooling application evaluation forms and transcript are requiredunited statesmasterslevel study college senior doctorallevel studi', 'applicant must be a college sophomore or junior enrolled or planning to enroll in a fulltime four or fiveyear abet or acceaccredited construction management or constructionrelated engineering program application evaluation forms and transcript are requiredunited statescollege senior college junior college sophomor', 'applicant must have a major that is considered beneficial to the new york state water works selection is based upon academic achievement and extracurricular activitiesnew yorkcollege senior college junior', 'applicant must be a us citizen or permanent us resident must have been a resident of virginia for at least one year prior to the deadline must be enrolled full time at an accredited college university or school of the arts and must submit slides of artwork for art three films for filmvideo or three research papers for art historyvirginiamasterslevel study college senior doctorallevel study college sophomore college freshman college junior', 'applicant must be a us citizen be a phd candidate have completed all requirements for the phd except the dissertation and have a dissertation topic focused on the history of visual arts of the us applicant must be enrolled at a us institution applications must be submitted through the acls online fellowship application system ofa ofa is accessible through the fellowship and grant programs section of the web siteno geographic restrictionsmasterslevel study doctorallevel studi', 'applicant must be a recently ordained rabbi award looks to help recipient obtain advanced training as a judge on rabbinical courts heads of institutions of higher learning or other advanced religious leadership positionsno geographic restrictionsno restrict', 'applicant must have a minimum gpa and major in the food science or food technology fieldsno geographic restrictionsdoctorallevel study masterslevel studi', 'applicant must have a minimum gpa conduct research in the area of food science or food technology and must demonstrate an interest in researchno geographic restrictionsmasterslevel study doctorallevel studi', 'applicant must be a connecticut resident with a predoctoral degree in dental medicineno geographic restrictionshigh school junior', 'applicant must be an outstanding graduate student in school administration who intends to make school superintendency a careerno geographic restrictionsmasterslevel study other postgraduatelevel study doctorallevel studi', 'applicant must be a recent graduate of a new hampshire high school who will be entering his or her first year of college to study education applicant must have a minimum grade average of bnew hampshirecollege freshman', 'applicant must be a fulltime graduate student in any field of education and a member in good standing of phi delta kappa selection based upon written essay transcript recommendation and involvement with phi delta kappano geographic restrictionsmasterslevel study other postgraduatelevel study doctorallevel studi', 'applicant must be a black or hispanic indiana resident with a minimum gpa who agrees to teach in indiana upon certification award may be used at indiana schools onlyindianacollege freshman college sophomore college senior college junior', 'applicant must be a current high school senior or college undergraduate student looking to or already majoring in education selection is based upon recommendations written essay academic standing and leadership activitiesno geographic restrictionshigh school senior', 'applicant must be a west virginia resident who are or will be enrolled on a fulltime basis in an accredited institution of higher education in west virginia pursuing a course of study leading to a teacher certificate at the preschoo

Applies `CountVectorizer` to convert cleaned text into numerical feature vectors.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
vector = cv.fit_transform(df['clean_text']).toarray()

Prints the number of unique words (features) identified by the vectorizer.

In [ ]:
len(cv.get_feature_names_out())

11009

Calculates cosine similarity between all scholarship description vectors.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

Defines a function to recommend scholarships based on similarity.

In [ ]:
def recommend(scholarship_name):
    if scholarship_name not in df['Scholarship Name'].values:
        return "Scholarship not found in the database."

    index = df[df['Scholarship Name'] == scholarship_name].index[0]

    distances = similarity[index]

    scholarship_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    print(f"'{scholarship_name}' - top 5 recommendations:")
    for i in scholarship_list:
        print(df.iloc[i[0]]['Scholarship Name'])

Demonstrates the recommendation function for a specific scholarship.

In [ ]:
recommend('Agnes Jones Jackson Scholarship')

'Agnes Jones Jackson Scholarship' - top 5 recommendations:
Roy Wilkins Scholarship
The HBCU Scholarship Fund
The Hubertus W.V. Willems Scholarship for Male Students
The Lillian &amp; Samuel Sutton Education Scholarship
The HBCU Scholarship Fund

Imports the `pickle` library.

In [ ]:
import pickle

Saves the DataFrame to a pickle file named 'schoolrship.pkl'.

In [ ]:
pickle.dump(df,open('schoolrship.pkl','wb'))

Saves the similarity matrix to a pickle file named 'similarity.pkl'.

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))